# Generated by Django 5.0 on 2024-10-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author_id',
            new_name='author',
        ),
    ]
